export const CREATE_CHAT = "CREATE_CHAT";
export const CREATE_GROUP = "CREATE_GROUP";
export const GET_USERS_CHAT = "GET_USERS_CHAT";
export const UPDATED_LAST_CHAT_MESSAGE = "UPDATED_LAST_CHAT_MESSAGE";
export const UPDATED_LAST_CHAT_COUNT = "UPDATED_LAST_CHAT_COUNT";



